import React , {useState} from "react";
import Head from 'next/head'
import ProductItem from "@/components/ProductItem";


export default function Home(props) {
  const [products , setProducts] = useState(props.products)


  return (
    <div className="row gap-3 m-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        products.length === 0 ? (
          <h2>Not Data Found!</h2>
        )
        : products.map((product) =>(
          <ProductItem key={product.id} product={product}/>
        ))
      }
    </div>
  )
}

// export async function getServerSideProps(){
//   const res = await getData("product");
//   console.log(res)
//   return {
//     props:{
//       products: res.products,
//       result: res.result
//     }
//   }
// }

export async function getServerSideProps(){
  const res = await fetch("http://localhost:3000/api/products");
  const data = await res.json();
  return {
    props:{
      products: data.products,
      result: data.result
    }
  }
}
