import Head from 'next/head'
import { getData } from "../utils/fetchData";


function Products() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        
      </main>
    </>
  )
}

// export async function getServerSideProps(){
//   const res = await getData("product");
//   console.log(res)
//   return {
//     props:{
//       products: res.products,
//       result: res.result
//     }
//   }
// }

export default Products;